package com.tips3x3.app;

/**
 * Scripts para ler saldo da Exchange no WebView (a API REST /account etc. retorna 404).
 * Espelha a lógica da extensão Bolsa Manual (DOM + storage + hook de fetch).
 */
final class BetBraBalanceJs {
  private BetBraBalanceJs() {}

  /** Instala hook de fetch/XHR e grava em window.__T33_LAST_BALANCE__. */
  static final String INSTALL_HOOK =
      "(function(){"
          + "if(window.__T33_BAL_HOOK__)return true;"
          + "window.__T33_BAL_HOOK__=true;"
          + "window.__T33_LAST_BALANCE__=window.__T33_LAST_BALANCE__||null;"
          + "var keys=['available-to-bet','available_to_bet','availableToBet',"
          + "'available-funds','available_funds','availableFunds',"
          + "'available-balance','availableBalance','balance','funds','wallet','saldo','available','amount','credit'];"
          + "function asMoney(v){"
          + "  if(typeof v==='number'&&isFinite(v)&&v>=0&&v<=5000000)return Math.round(v*100)/100;"
          + "  if(typeof v==='string'){"
          + "    var s=v.trim();"
          + "    if(/^\\d+([.,]\\d+)?$/.test(s)){var n=Number(s.replace(',','.'));"
          + "      if(isFinite(n)&&n>=0&&n<=5000000)return Math.round(n*100)/100;}"
          + "  }"
          + "  return null;"
          + "}"
          + "function extract(data,depth){"
          + "  if(data==null||depth>7)return null;"
          + "  if(typeof data!=='object')return asMoney(data);"
          + "  for(var i=0;i<keys.length;i++){"
          + "    var k=keys[i];"
          + "    if(data[k]!=null){"
          + "      var n=asMoney(data[k]);"
          + "      if(n!=null)return n;"
          + "      if(typeof data[k]==='object'){n=extract(data[k],depth+1);if(n!=null)return n;}"
          + "    }"
          + "  }"
          + "  for(var kk in data){"
          + "    if(!Object.prototype.hasOwnProperty.call(data,kk))continue;"
          + "    if(/available[-_]?to[-_]?bet|availableToBet/i.test(kk)){"
          + "      var nn=asMoney(data[kk]);if(nn!=null)return nn;"
          + "    }"
          + "  }"
          + "  var nests=['account','accounts','wallet','funds','member','user','data','result'];"
          + "  for(var j=0;j<nests.length;j++){"
          + "    if(data[nests[j]]!=null){var m=extract(data[nests[j]],depth+1);if(m!=null)return m;}"
          + "  }"
          + "  if(Array.isArray(data)){"
          + "    for(var a=0;a<Math.min(data.length,20);a++){"
          + "      var x=extract(data[a],depth+1);if(x!=null)return x;"
          + "    }"
          + "  }"
          + "  return null;"
          + "}"
          + "function consider(url,data){"
          + "  try{"
          + "    if(!/balance|wallet|fund|account|member|saldo|exposure|available|user/i.test(String(url||'')))return;"
          + "    var bal=extract(data);"
          + "    if(bal!=null)window.__T33_LAST_BALANCE__=bal;"
          + "  }catch(e){}"
          + "}"
          + "try{"
          + "  var ofetch=window.fetch&&window.fetch.bind(window);"
          + "  if(ofetch){"
          + "    window.fetch=function(){"
          + "      var args=arguments;"
          + "      return ofetch.apply(window,args).then(function(res){"
          + "        try{"
          + "          var u=(args[0]&&args[0].url)||args[0]||'';"
          + "          res.clone().json().then(function(d){consider(u,d);}).catch(function(){});"
          + "        }catch(e){}"
          + "        return res;"
          + "      });"
          + "    };"
          + "  }"
          + "}catch(e){}"
          + "try{"
          + "  var XO=XMLHttpRequest.prototype.open;"
          + "  var XS=XMLHttpRequest.prototype.send;"
          + "  XMLHttpRequest.prototype.open=function(m,u){this.__t33u=u;return XO.apply(this,arguments);};"
          + "  XMLHttpRequest.prototype.send=function(){"
          + "    var xhr=this;"
          + "    this.addEventListener('load',function(){"
          + "      try{consider(xhr.__t33u,JSON.parse(xhr.responseText));}catch(e){}"
          + "    });"
          + "    return XS.apply(this,arguments);"
          + "  };"
          + "}catch(e){}"
          + "return true;"
          + "})();";

  /** Lê saldo: hook → storage → DOM. Retorna número ou null (JSON). */
  static final String READ_BALANCE =
      "(function(){"
          + "function parseBrl(raw){"
          + "  var s=String(raw||'').replace(/\\u00a0/g,' ');"
          + "  var m=s.match(/R\\$\\s*([\\d.]+),(\\d{2})/);"
          + "  if(m)return Number(m[1].replace(/\\./g,'')+'.'+m[2]);"
          + "  m=s.match(/R\\$\\s*([\\d,]+)\\.(\\d{2})/);"
          + "  if(m)return Number(m[1].replace(/,/g,'')+'.'+m[2]);"
          + "  m=s.match(/R\\$\\s*(\\d+(?:[.,]\\d{1,2})?)/);"
          + "  if(m)return Number(m[1].replace(',','.'));"
          + "  m=s.match(/^([\\d.]+),(\\d{2})$/);"
          + "  if(m)return Number(m[1].replace(/\\./g,'')+'.'+m[2]);"
          + "  return null;"
          + "}"
          + "function asMoney(v){"
          + "  if(typeof v==='number'&&isFinite(v)&&v>=0&&v<=5000000)return Math.round(v*100)/100;"
          + "  if(typeof v==='string'){"
          + "    var p=parseBrl(v);if(p!=null&&p>=0&&p<=5000000)return Math.round(p*100)/100;"
          + "    if(/^\\d+([.,]\\d+)?$/.test(v.trim())){"
          + "      var n=Number(v.trim().replace(',','.'));"
          + "      if(isFinite(n)&&n>=0&&n<=5000000)return Math.round(n*100)/100;"
          + "    }"
          + "  }"
          + "  return null;"
          + "}"
          + "var cands=[];"
          + "function push(n,w,via){"
          + "  if(n==null||!isFinite(n)||n<0||n>5000000)return;"
          + "  cands.push({b:Math.round(n*100)/100,w:w,via:via});"
          + "}"
          + "try{if(window.__T33_LAST_BALANCE__!=null)push(window.__T33_LAST_BALANCE__,80,'hook');}catch(e){}"
          + "try{"
          + "  for(var si=0;si<2;si++){"
          + "    var store=si===0?localStorage:sessionStorage;"
          + "    for(var i=0;i<store.length;i++){"
          + "      var k=store.key(i)||'';"
          + "      if(!/saldo|balance|wallet|fund|available|user|account/i.test(k))continue;"
          + "      var raw=store.getItem(k);if(!raw)continue;"
          + "      push(parseBrl(raw),-20,'storage');"
          + "      try{"
          + "        var j=JSON.parse(raw);var stack=[j];var g=0;"
          + "        while(stack.length&&g++<80){"
          + "          var cur=stack.pop();if(!cur||typeof cur!=='object')continue;"
          + "          for(var kk in cur){"
          + "            if(!Object.prototype.hasOwnProperty.call(cur,kk))continue;"
          + "            var vv=cur[kk];"
          + "            if(/available[-_]?to[-_]?bet|availableToBet/i.test(kk)){"
          + "              push(typeof vv==='number'?vv:parseBrl(String(vv)),40,'storage-json');"
          + "            }else if(/saldo|balance|available|fund|wallet|amount|credit/i.test(kk)){"
          + "              if(typeof vv==='number')push(vv,-10,'storage-json');"
          + "              else push(parseBrl(String(vv)),-10,'storage-json');"
          + "            }else if(vv&&typeof vv==='object')stack.push(vv);"
          + "          }"
          + "        }"
          + "      }catch(e){}"
          + "    }"
          + "  }"
          + "}catch(e){}"
          + "try{"
          + "  var root=document.body||document.documentElement;if(root){"
          + "    var sel=\"header,nav,[class*='balance'],[class*='Balance'],[class*='saldo'],[class*='Saldo'],[class*='wallet'],[class*='Wallet'],[class*='fund'],[class*='header'],[class*='Header'],[data-balance],[data-saldo]\";"
          + "    var nodes=root.querySelectorAll(sel);"
          + "    for(var ni=0;ni<nodes.length;ni++)push(parseBrl(nodes[ni].textContent||''),25,'dom-attr');"
          + "    var blob=(root.innerText||'').replace(/\\s+/g,' ');"
          + "    var re=/(?:Saldo(?:\\s*(?:dispon[ií]vel|da\\s*conta)?)?|Dispon[ií]vel|Balance|Available|Carteira)[^\\dR$]{0,32}(R\\$\\s*[\\d.,]+|[\\d.]+,\\d{2})/gi;"
          + "    var m;while((m=re.exec(blob))){"
          + "      push(parseBrl(m[1].indexOf('R$')===0?m[1]:('R$ '+m[1])),50,'dom-label');"
          + "    }"
          + "  }"
          + "}catch(e){}"
          + "if(!cands.length)return null;"
          + "cands.sort(function(a,b){return b.w!==a.w?b.w-a.w:a.b-b.b;});"
          + "var trusted=cands.filter(function(c){return c.w>=25;});"
          + "var pool=trusted.length?trusted:cands.filter(function(c){return c.w>=0;});"
          + "var use=pool.length?pool:cands;"
          + "var wallet=use.filter(function(c){return c.b<=50000;});"
          + "var pick=(wallet.length?wallet:use)[0];"
          + "return pick?pick.b:null;"
          + "})();";
}
