let running=false;
export function installSurebetWorker(config){
 const ALARM=`surebet-${config.venue}`;
 chrome.runtime.onInstalled.addListener(()=>chrome.alarms.create(ALARM,{periodInMinutes:0.5}));
 chrome.runtime.onStartup.addListener(()=>chrome.alarms.create(ALARM,{periodInMinutes:0.5}));
 chrome.alarms.onAlarm.addListener(a=>{if(a.name===ALARM)scan(config)});
 chrome.runtime.onMessage.addListener((m,_s,reply)=>{if(m?.type==="SCAN_NOW"){scan(config).then(()=>reply({ok:true}));return true;}});
}
const defaults={enabled:false,prelive:true,live:true,budget:100,commission:5,minRoi:0.1};
async function tokenFor(config){for(const domain of [new URL(config.api).hostname,new URL(config.web).hostname]){const all=await chrome.cookies.getAll({domain});for(const c of all){if(/session[-_]?token|access[-_]?token|authorization/i.test(c.name)&&c.value)return c.value;}}return "";}
async function api(config,path,options={}){const token=await tokenFor(config);if(!token)throw new Error(`${config.label} desconectada: faça login no site da exchange`);const headers={Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{})};headers.Authorization=`Bearer ${token}`;const r=await fetch(config.api+path,{...options,headers,credentials:"include"});const text=await r.text();let body={};try{body=text?JSON.parse(text):{};}catch{}if(!r.ok)throw new Error(`${config.label} HTTP ${r.status}${body?.message?`: ${body.message}`:""}`);return body;}
function items(body){return body?.events||body?.items||(Array.isArray(body?.data)?body.data:null)||body?.data?.events||body?.data?.items||body?.data?.results||body?.results||[];}
function hasMore(body,offset,count,size){const s=body?.pagination||body?.meta||body?.data?.pagination||body?.data?.meta||body;if("has-more" in s)return !!s["has-more"];if("has_more" in s)return !!s.has_more;if("hasMore" in s)return !!s.hasMore;const next=s.next??s["next-page"]??s.next_page;if(next!=null)return next!==false&&String(next)!=="";const total=s.total??s["total-count"]??s.total_count??s.totalCount;return Number.isFinite(Number(total))?offset+count<Number(total):count>=size;}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();}
function marketKind(m){const n=norm(m?.["name-original"]||m?.name);if(n==="match odds"||n==="resultado da partida")return"match-odds";if(n==="half time"||/(half time result|first half result|1st half result|resultado.*1.*tempo|intervalo)/.test(n))return"first-half";return null;}
function quote(m){const rs=m?.runners;if(!Array.isArray(rs)||rs.length!==3)return null;const q={marketId:String(m.id||"")};let team=0;for(const r of rs){const name=String(r.name||"");const key=/(draw|empate)/i.test(name)?"draw":(team++===0?"home":"away");let best=null;for(const p of r.prices||[]){if(norm(p.side)!=="back")continue;const odds=Number(p.odds),liquidity=Number(p["available-amount"]??p.availableAmount??0);if(odds>1.01&&liquidity>0&&(!best||odds>best.odds))best={odds,liquidity};}if(!best)return null;q[key]={name,runnerId:String(r.id||""),...best};}return q.home&&q.draw&&q.away?q:null;}
function minute(e){for(const v of [e.minute,e["match-minute"],e.elapsed,e.clock?.minute,e.live?.minute]){const n=parseInt(v,10);if(Number.isFinite(n))return n;}const t=String(e.clock||e.timer||"");const m=t.match(/(\d{1,3})/);return m?Number(m[1]):0;}
function calculate(q,s){const fee=Math.max(0,Math.min(100,s.commission))/100,keys=["home","draw","away"],eff=[],sel=[];let inv=0;for(const k of keys){const x=q[k];if(!x||x.odds<=1.01||x.liquidity<1)return null;sel.push(x);const e=1+(x.odds-1)*(1-fee);eff.push(e);inv+=1/e;}if(inv>=1)return null;let budget=Math.max(3,s.budget),payout=budget/inv,scale=1;for(let i=0;i<3;i++)scale=Math.min(scale,sel[i].liquidity/(payout/eff[i]));budget=Math.floor(budget*Math.min(1,scale)*100)/100;payout=budget/inv;const legs=[];let used=0;for(let i=0;i<3;i++){const stake=Math.min(Math.floor(payout/eff[i]*100)/100,Math.floor(sel[i].liquidity*100)/100);if(stake<1)return null;used+=stake;legs.push({result:keys[i],name:sel[i].name,runnerId:sel[i].runnerId,odds:sel[i].odds,stake,liquidity:sel[i].liquidity});}let profit=Infinity;for(let i=0;i<3;i++)profit=Math.min(profit,legs[i].stake+legs[i].stake*(legs[i].odds-1)*(1-fee)-used);const roi=profit/used*100;if(profit<=0||roi<s.minRoi)return null;return{legs,totalStake:Math.round(used*100)/100,netProfit:Math.floor(profit*100)/100,roi:Math.floor(roi*100)/100,adjusted:scale<.999999};}
async function authorized(){const r=await fetch("https://tips3x3.com/api/auth/me",{credentials:"include"});return r.ok;}
async function report(config,o){try{await fetch("https://tips3x3.com/api/indications",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"surebet",eventId:o.eventId,eventName:o.eventName,marketName:o.kind==="first-half"?"Resultado do Primeiro Tempo":"Match Odds",scoreLabel:o.phase,stake:o.totalStake,liability:o.totalStake,expectedProfit:o.netProfit,realizedProfit:o.netProfit,appProduct:config.product,surebetLegs:o.legs.map(x=>({selection:x.name,venue:config.venue,odds:x.odds,stake:x.stake})),source:"extension",event:{type:"green",stake:o.totalStake,profit:o.netProfit}})});}catch{}}
async function scan(config){if(running)return;running=true;try{const s=await chrome.storage.sync.get(defaults);if(s.enabled&&!(await authorized()))throw new Error("Acesso Tips3x3 inválido: entre no painel antes de ativar");const names=encodeURIComponent("Match Odds,Half Time,Half Time Result,First Half Result"),size=100,seenPages=new Set(),seenEvents=new Set(),opps=[];let offset=0;while(true){const body=await api(config,`/events?offset=${offset}&per-page=${size}&sport-ids=15&sort-by=start&sort-direction=asc&en-market-names=${names}&market-types=one_x_two&odds-type=DECIMAL&price-depth=3`);const es=items(body);if(!es.length)break;const fp=es.map(e=>e?.id||"?").join("|");if(seenPages.has(fp))break;seenPages.add(fp);for(const e of es){const id=String(e?.id||"");if(!id||seenEvents.has(id))continue;seenEvents.add(id);const isLive=!!(e["in-running-flag"]??e.inRunning??e.live);if((isLive&&!s.live)||(!isLive&&!s.prelive)||(isLive&&minute(e)>60))continue;for(const m of e.markets||[]){const kind=marketKind(m);if(!kind)continue;const q=quote(m),calc=q&&calculate(q,s);if(calc)opps.push({...calc,eventId:id,eventName:e.name||"Partida",marketId:q.marketId,kind,phase:isLive?`live ${minute(e)}'`:"prelive"});}}
 if(!hasMore(body,offset,es.length,size))break;offset+=es.length;if(offset>100000)break;}
 const done=(await chrome.storage.local.get({executed:{}})).executed;for(const o of opps){const key=`${o.eventId}:${o.marketId}:${o.kind}`;if(!s.enabled||done[key])continue;const fresh=await api(config,`/events/${encodeURIComponent(o.eventId)}?odds-type=DECIMAL&price-depth=3`);const event=fresh.event||fresh;const m=(event.markets||[]).find(x=>String(x.id)===String(o.marketId)&&marketKind(x)===o.kind);const calc=m&&calculate(quote(m),s);if(!calc)continue;done[key]=Date.now();await chrome.storage.local.set({executed:done});const payload={"odds-type":"DECIMAL","exchange-type":"back-lay",offers:calc.legs.map(x=>({"runner-id":x.runnerId,"event-id":o.eventId,"market-id":o.marketId,side:"back",odds:x.odds,stake:x.stake,"keep-in-play":false}))};try{await api(config,"/offers",{method:"POST",body:JSON.stringify(payload)});}catch(err){delete done[key];await chrome.storage.local.set({executed:done});throw err;}const placed={...o,...calc};await report(config,placed);await chrome.notifications.create({type:"basic",iconUrl:"icons/icon128.png",title:`Surebet ${config.label} executada`,message:`${o.eventName} · R$ ${calc.totalStake.toFixed(2)} · lucro R$ ${calc.netProfit.toFixed(2)}`});await chrome.storage.local.set({lastOrder:`${o.eventName} · R$ ${calc.totalStake.toFixed(2)}`});}
 await chrome.storage.local.set({status:`${config.label} conectada`,lastError:"",lastScanAt:Date.now(),lastOpportunities:opps.length});}catch(e){await chrome.storage.local.set({lastError:String(e?.message||e),lastScanAt:Date.now()});}finally{running=false;}}
